#!/bin/bash

DOTFILES_WORK_TREE_PATH=$HOME
DOTFILES_GIT_PATH=$HOME/.dotfiles

DOTFILES_ORIGIN_REMOTE=origin
DOTFILES_BACKUP_REMOTE=backup
DOTFILES_TEMPLATE_REMOTE=template

DOTFILES_DEFAULT_BRANCH=main
DOTFILES_BACKUP_BRANCH=backup-mac

function dotfiles {
  git --work-tree=$DOTFILES_WORK_TREE_PATH --git-dir=$DOTFILES_GIT_PATH "$@"
}
